/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.22                          *
*        Compiled Jul  4 2013, 15:16:01                              *
*        (c) 2013 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "wt_bsp_storage.h"
#include "wt_task_gui.h"
#include "wt_bsp_key_led.h"
#include "k_rtc.h"
#include "wt_bsp_file.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 			(GUI_ID_USER + 0x00)
#define ID_BUTTON_OK 			(GUI_ID_USER + 0x01)
#define ID_TEXT_0 				(GUI_ID_USER + 0x02)
#define ID_BUTTON_CANCEL 	(GUI_ID_USER + 0x03)
#define ID_IMAGE_0 				(GUI_ID_USER + 0x04)


extern GUI_CONST_STORAGE GUI_BITMAP bm_warn_120x100;
// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 80, 0, 320, 222, 0, 0x0, 0 },
//	{ FRAMEWIN_CreateIndirect, "Dialgo",  ID_DIALOG_0, 100, 0, 280, 222, 0, 0x0, 0},
//	{ WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 100, 0, 280, 222, 0, 0x0, 0 },
//  { BUTTON_CreateIndirect, "确定", ID_BUTTON_OK, 40, 153, 80, 20, 0, 0x0, 0 },
//  { BUTTON_CreateIndirect, "取消", ID_BUTTON_CANCEL, 130, 153, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_0, 50, 40, 220, 70, 0, 0x64, 0 },
	{ IMAGE_CreateIndirect, "Image1", ID_IMAGE_0, 100, 75, 120, 100, 0, 0, 0 },
	{	BUTTON_CreateIndirect, "确定", ID_BUTTON_OK, 60, 200, 100, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "取消", ID_BUTTON_CANCEL, 160, 200, 100, 20, 0, 0x0, 0 },

  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
	WM_MESSAGE Msg;
	WM_HWIN hParent;
  // USER START (Optionally insert additional variables)
  // USER END
	hItem = pMsg->hWin;
	WINDOW_SetBkColor(hItem, GUI_WHITE);

	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_OK);
	BUTTON_SetFont(hItem,&GUI_FontHZ12);
	BUTTON_SetSkinClassic(hItem);
	BUTTON_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	BUTTON_SetBkColor(hItem,BUTTON_CI_UNPRESSED, GUI_GREEN);
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_CANCEL);
	BUTTON_SetFont(hItem,&GUI_FontHZ12);
	BUTTON_SetSkinClassic(hItem);
	BUTTON_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	BUTTON_SetBkColor(hItem,BUTTON_CI_UNPRESSED, GUI_RED);
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_0);
	IMAGE_SetBitmap(hItem, &bm_warn_120x100);
	
  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:

	  hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetFont(hItem,&GUI_FontHZ12);
		TEXT_SetTextAlign(hItem,TEXT_CF_LEFT);
    TEXT_SetText(hItem, (char *)" 警告：是否关闭当前运行的程序？");  
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
	case WM_KEY:
		GUI_SendKeyMsg(GUI_KEY_TAB, 1);//改变输入焦点
		break;
	case MY_MESSAGE_OK:
		Msg.MsgId = MY_MESSAGE_OK;
		hItem = pMsg->hWin;
		hParent=WM_GetParent(hItem);
		WM_SendMessage(hParent,&Msg);//将消息发送到控件所属窗口
		GUI_EndDialog(pMsg->hWin,0);
		break;
	case WM_PAINT://绘制标题栏
		GUI_SetColor(GUI_DARKBLUE);
		GUI_FillRect(0,0,320,22);
		GUI_SetColor(GUI_DARKGRAY);
		GUI_SetPenSize(8);
		//GUI_DrawRect(0,0,318,220);
		GUI_DrawRoundedFrame(0, 0, 318, 222, 0, 2);
    break;
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN CreateWarningBox(WM_HWIN hWin_para);
WM_HWIN CreateWarningBox(WM_HWIN hWin_para) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, hWin_para, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
