/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.22                          *
*        Compiled Jul  4 2013, 15:16:01                              *
*        (c) 2013 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END
#define WT_WINDOWS_PASSWD_GLOBALS

#include "DIALOG.h"
#include "wt_bsp.h"
#include "wt_task_gui.h"
#include "main.h"

#include "tools.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0     		(GUI_ID_USER + 0x00)
#define ID_TEXT_TITLE     	(GUI_ID_USER + 0x01)
#define ID_TEXT_RESULT    	(GUI_ID_USER + 0x02)
#define ID_TEXT_PASSWD    	(GUI_ID_USER + 0x03)
#define ID_BUTTON_OK     		(GUI_ID_USER + 0x04)
#define ID_BUTTON_CANCEL    (GUI_ID_USER + 0x05)
#define ID_EDIT_USERNAME    (GUI_ID_USER + 0x06)
#define ID_EDIT_PASSWD    	(GUI_ID_USER + 0x07)




// USER START (Optionally insert additional defines)
// USER END

static int cursorindex=0;

extern uint8_t WT_Config_Passwd_Read(void);
														
/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0,    		 80,   0, 320, 222, 0, 0x0, 0 },
	{ TEXT_CreateIndirect, "Title", ID_TEXT_TITLE, 			 120, 60, 220, 70, 0, 0x64, 0 },
	{ EDIT_CreateIndirect, "Edit-passwd", ID_EDIT_PASSWD, 100, 100, 120, 40, 0, 0x64, 0 },
	{ TEXT_CreateIndirect, "Result", ID_TEXT_RESULT, 			 100, 150, 200, 20, 0, 0x64, 0 },
	{	BUTTON_CreateIndirect, "确定", ID_BUTTON_OK, 60, 200, 100, 20, 0, 0x0, 0},
  { BUTTON_CreateIndirect, "取消", ID_BUTTON_CANCEL, 160, 200, 100, 20, 0, 0x0, 0},
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN                hItem;
	WM_MESSAGE             Msg;
	int cursorpos=0;
	uint8_t NumChars=0;
	int index=0;
	char passwd[8];
	uint8_t res=0;
	memset(passwd,0,8);
    
	hItem = pMsg->hWin;
	WINDOW_SetBkColor(hItem, GUI_LIGHTGRAY);
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_USERNAME);
	WM_SetFocus(hItem);

  switch (pMsg->MsgId) {
    case WM_INIT_DIALOG:
        Wheel_Encoder_Write(0);//wheel清零
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_TITLE);
        TEXT_SetFont(hItem,&GUI_FontHZ12);
        TEXT_SetText(hItem, "输入管理密码"); 

        hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_PASSWD);
        EDIT_SetFont(hItem,GUI_FONT_32_1);
        EDIT_SetMaxLen(hItem, 6);
        EDIT_EnableBlink(hItem, 600, 1);
        EDIT_SetInsertMode(hItem,1);	
        cursorindex=EDIT_GetCursorCharPos(hItem);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_RESULT);
        TEXT_SetFont(hItem,&GUI_FontHZ12);
        TEXT_SetTextColor(hItem,GUI_RED);  
        TEXT_SetText(hItem, "");  


        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_OK);
        BUTTON_SetFont(hItem,&GUI_FontHZ12);
        BUTTON_SetSkinClassic(hItem);
        BUTTON_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
        BUTTON_SetBkColor(hItem,BUTTON_CI_UNPRESSED, GUI_GREEN);
        BUTTON_SetFocussable(hItem,0);//不接收焦点

        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_CANCEL);
        BUTTON_SetFont(hItem,&GUI_FontHZ12);
        BUTTON_SetSkinClassic(hItem);
        BUTTON_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
        BUTTON_SetBkColor(hItem,BUTTON_CI_UNPRESSED, GUI_RED);
        BUTTON_SetFocussable(hItem,0);//不接收焦点
        // USER START (Optionally insert additional code for further widget initialization)
        // USER END
        break;
	case MY_MESSAGE_OK:
		res = WT_Config_Passwd_Read();
		if(res != 0) break;
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_PASSWD);
		EDIT_GetText(hItem,passwd,8);
		if(strncmp((char *)WT_Config.Passwd,passwd,6) == 0)//密码正确
		{			
			Msg.MsgId = MY_MESSAGE_BUTTONOK;
			WM_SendMessage(pMsg->hWinSrc,&Msg);
			GUI_EndDialog(pMsg->hWin,0);
		}
		else
		{
			hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_RESULT);
			TEXT_SetFont(hItem,&GUI_FontHZ12);
			TEXT_SetText(hItem, "密码输入错误！"); 
			//WM_SetFocus(hItem);
		}  
		break;
	case MY_MESSAGE_CANCEL://取消
		TestFile->command=2;//test cancel
		TestFile->item_total=0;
		GUI_EndDialog(pMsg->hWin,0);
		break;
	case MY_MESSAGE_CLICK:
		GUI_SendKeyMsg(GUI_KEY_TAB, 1);//改变输入焦点
		break;
	case MY_MESSAGE_DOWN:
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_PASSWD);	
		cursorpos=EDIT_GetCursorCharPos(hItem);
		NumChars = EDIT_GetNumChars(hItem);
		if(cursorpos <= (NumChars-1) )
		{
			EDIT_SetCursorAtChar(hItem,cursorpos+1);
			EDIT_SetSel(hItem,cursorpos+1,cursorpos+1);
			cursorindex=EDIT_GetCursorCharPos(hItem);
		}
		//GUI_Exec();
		break;
	case MY_MESSAGE_UP:
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_PASSWD);
		cursorpos=EDIT_GetCursorCharPos(hItem);
		EDIT_SetCursorAtChar(hItem,cursorpos-1);
		EDIT_SetSel(hItem,cursorpos-1,cursorpos-1);
		cursorindex=EDIT_GetCursorCharPos(hItem);
		//GUI_Exec();
		break;
	case MY_MESSAGE_WHEEL://处理滚轮事件
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_PASSWD);
		EDIT_SetCursorAtChar(hItem,cursorindex);
		index = Get_InputChar_Index(Wheel_Encoder_Read());

		if(cursorindex==EDIT_GetCursorCharPos(hItem))
		{
			EDIT_AddKey(hItem,GUI_KEY_DELETE);
			EDIT_AddKey(hItem,Get_InputChar(index));
			cursorpos=EDIT_GetCursorCharPos(hItem);
			EDIT_SetSel(hItem,cursorpos-1,cursorpos-1);
		}
		GUI_Exec();
		break;
	case MY_MESSAGE_BUTTONDELETE://删除字符
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_PASSWD);
		if(WM_HasFocus(hItem))
		{
			EDIT_AddKey(hItem,GUI_KEY_BACKSPACE);
			cursorindex=EDIT_GetCursorCharPos(hItem);
		}
		break;
	case WM_PAINT://绘制标题栏
		GUI_SetColor(GUI_DARKBLUE);
		GUI_FillRect(0,0,320,22);
		GUI_SetColor(GUI_DARKGRAY);
		GUI_SetPenSize(2);
		GUI_DrawRect(0,0,318,220);
//		GUI_DrawRoundedFrame(0, 0, 480, 222, 0, 4);
    break;
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN Create_PasswdDlgWindow( WM_HWIN hWin_para);
WM_HWIN Create_PasswdDlgWindow( WM_HWIN hWin_para) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, hWin_para, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
