/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.22                          *
*        Compiled Jul  4 2013, 15:16:01                              *
*        (c) 2013 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END
#define WT_WINDOWS_TEST_GLOBALS

#include "DIALOG.h"
#include "wt_bsp.h"
#include "wt_task_gui.h"
#include "wt_task_wirestudy.h"
#include "wt_task_wireselfcheck.h"
#include "main.h"
#include "tools.h"



/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0     			(GUI_ID_USER + 0x00)
#define ID_TEXT_0     				(GUI_ID_USER + 0x02)
#define ID_TEXT_1     				(GUI_ID_USER + 0x03)
#define ID_BUTTON_OK     			(GUI_ID_USER + 0x04)
#define ID_BUTTON_CANCEL     	    (GUI_ID_USER + 0x05)
#define ID_PROGBAR0					(GUI_ID_USER + 0x06)
#define ID_TEXT_BOARD_SELECT        (GUI_ID_USER + 0x07)
#define ID_EDIT_BOARD_SELECT        (GUI_ID_USER + 0x08)




/*********************************************************************
*
*       Static data
*
**********************************************************************
*/


/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 100, 0, 280, 222, 0, 0x0, 0 },
	{ TEXT_CreateIndirect, "InputPortNum", ID_TEXT_0, 40, 50, 110, 20, 0, 0x0, 0 },
	{ TEXT_CreateIndirect, "PortNum", ID_TEXT_1, 150, 50, 110, 20, 0, 0x0, 0 },
	{ PROGBAR_CreateIndirect, "ProgBar",  ID_PROGBAR0,   30, 120, 220,  18},
	{	BUTTON_CreateIndirect, "开始自学习", ID_BUTTON_OK, 40, 180, 100, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "取消", ID_BUTTON_CANCEL, 140, 180, 100, 20, 0, 0x0, 0 },
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
    WM_HWIN                hItem;
    WM_MESSAGE             Msg;
    PROGBAR_Handle hProg;

    char num[3];
    int32_t sum=0;
    int32_t i=0;

	hItem = pMsg->hWin;
	WINDOW_SetBkColor(hItem, GUI_LIGHTGRAY);
		
  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetFont(hItem,&GUI_FontHZ16);
    TEXT_SetText(hItem, "连接板卡数量：");  
	
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
		TEXT_SetFont(hItem,&GUI_FontHZ16);
//		if(SelfCheckItem.port_board_number == 0)
//		{
//			osMessagePut(WireSelfCheckEvent, WIRESELFCHECK_START_EVENT, 0);//开始自检
//			i=100;
//			while(i--)
//			{
//				osDelay(10);
//				if(SelfCheckItem.state == 0) break;
//			}
//		}
    
		TEXT_SetText(hItem,itoa(SelfCheckItem.port_board_number,num,10)); 
    
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_OK);
		BUTTON_SetFont(hItem,&GUI_FontHZ12);
		BUTTON_SetSkinClassic(hItem);
		BUTTON_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
        BUTTON_SetBkColor(hItem,BUTTON_CI_UNPRESSED, GUI_GREEN);
		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_CANCEL);
		BUTTON_SetFont(hItem,&GUI_FontHZ12);
		BUTTON_SetSkinClassic(hItem);
		BUTTON_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
        BUTTON_SetBkColor(hItem,BUTTON_CI_UNPRESSED, GUI_RED);

	
		hItem = WM_GetDialogItem(pMsg->hWin, ID_PROGBAR0);  
		PROGBAR_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
        PROGBAR_SetFont(hItem, &GUI_FontHZ12);
		
		if(SelfCheckItem.port_board_number<=0)
		{
			hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_OK);
			TEXT_SetBkColor(hItem, GUI_LIGHTGRAY);
		}

    break;
	case WM_KEY:
		GUI_SendKeyMsg(GUI_KEY_TAB, 1);//改变输入焦点
		break;
	case MY_MESSAGE_WHEEL:
		break;
	case MY_MESSAGE_CANCEL://取消
		StudyFile->command=2;//study cancel
		GUI_EndDialog(pMsg->hWin,0);
		break;
	case MY_MESSAGE_OK:
		wt_SetText_Status("开始自学习");
		GUI_Exec();
		hProg = WM_GetDialogItem(pMsg->hWin, ID_PROGBAR0);
		PROGBAR_SetValue(hProg, 0);
		
		sum = add(SelfCheckItem.port_board_number*64);
		if(sum==0) 
		{	
			break;
		}
		PROGBAR_SetMinMax(hProg, 0, sum);
		//开始学习
		osMessagePut(WireStudyEvent, WIRESTUDY_START_EVENT, 0);
		while(1)
		{
			GUI_Delay(1000);
			if(StudyFile->item_index >= sum) break;
			PROGBAR_SetValue(hProg, StudyFile->item_index);
			if(StudyFile->task_status == 3) wt_SetText_Status("自学习错误");	
			//取消自学习
			if(BSP_GetKEY_State(KeyCancle) == 1 )
			{
				while(BSP_GetKEY_State(KeyCancle) == 1)
				{
					i++;
					osDelay(100);
				}
				if(i < 20)
				{
					StudyFile->command=2;//study cancel
					LED4_OFF();
					Msg.MsgId = MY_MESSAGE_BUTTONCANCEL;
					WM_SendMessage(pMsg->hWinSrc,&Msg);
					GUI_EndDialog(pMsg->hWin,0);
					break;
				}
			}
		}

		if(StudyFile->command!=2)//0-no operate, 1-start, 2-cancel
		{
			//开始自学习优化
			osMessagePut(WireStudyEvent, WIRESTUDY_OPTIMIZE_EVENT, 0);
			wt_SetText_Status("自学习优化");
			osDelay(500);
			for(;;)
			{
				if(StudyFile->task_status == 0)
					break;
			}
			Msg.MsgId = MY_MESSAGE_BUTTONOK;
			WM_SendMessage(pMsg->hWinSrc,&Msg);
			GUI_EndDialog(pMsg->hWin,0);
		}
		break;
	case WM_PAINT://绘制标题栏
		GUI_SetColor(GUI_DARKBLUE);
		GUI_FillRect(0,0,280,22);
		GUI_SetColor(GUI_DARKGRAY);
		GUI_SetPenSize(8);
		GUI_DrawRect(0,0,278,218);
    break;
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN Create_StudyDlgWindow( WM_HWIN hWin_para);
WM_HWIN Create_StudyDlgWindow( WM_HWIN hWin_para) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, hWin_para, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
