/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.22                          *
*        Compiled Jul  4 2013, 15:16:01                              *
*        (c) 2013 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "wt_bsp.h"
#include "wt_task_gui.h"
#include "main.h"


/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 			(GUI_ID_USER + 0x00)
#define ID_TEXT_1 				(GUI_ID_USER + 0x01)
#define ID_IMAGE_0 				(GUI_ID_USER + 0x02)

extern GUI_CONST_STORAGE GUI_BITMAP bmbm_test_ok;
// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 120, 22, 240, 180, 0, 0x0, 0 },
  //{ TEXT_CreateIndirect, "Text", ID_TEXT_0, 60, 80, 60, 20, 0, 0x64, 0 },
	{ IMAGE_CreateIndirect, "Image", ID_IMAGE_0, 0, 0, 240, 180, 0, 0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  // USER START (Optionally insert additional variables)
  // USER END
		hItem = pMsg->hWin;
	WINDOW_SetBkColor(hItem, GUI_LIGHTGRAY);

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
	  hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_0);
		IMAGE_SetBitmap(hItem, &bmbm_test_ok);
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case MY_MESSAGE_OK:
		GUI_EndDialog(pMsg->hWin,0);
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN CreateTestOKBox(WM_HWIN hWin_para);
WM_HWIN CreateTestOKBox(WM_HWIN hWin_para) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, hWin_para, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
