/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.22                          *
*        Compiled Jul  4 2013, 15:16:01                              *
*        (c) 2013 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END
#define WT_WINDOWS_TEST_GLOBALS

#include "DIALOG.h"
#include "wt_bsp.h"
#include "wt_task_gui.h"
#include "main.h"


/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0     		(GUI_ID_USER + 0x00)
#define ID_LISTBOX_0    		(GUI_ID_USER + 0x01)
#define ID_TEXT_0     			(GUI_ID_USER + 0x02)
#define ID_TREEVIEW_0     	(GUI_ID_USER + 0x03)
#define ID_BUTTON_OK     		(GUI_ID_USER + 0x04)
#define ID_BUTTON_CANCEL    (GUI_ID_USER + 0x05)
#define ID_TEXT_1     			(GUI_ID_USER + 0x06)
#define ID_DROPDOWN_0    		(GUI_ID_USER + 0x07)
#define ID_TEXT_LOCKINFO    (GUI_ID_USER + 0x08)
#define ID_TEXT_PPID        (GUI_ID_USER + 0x09)
#define ID_TEXT_PPID_TITLE  (GUI_ID_USER + 0x0A)
#define ID_TEXT_TESTMODEINF (GUI_ID_USER + 0x0B)
#define ID_TEXT_TESTMODE    (GUI_ID_USER + 0x0C)


// USER START (Optionally insert additional defines)
// USER END
extern uint8_t WT_StoreFiles_Init(void);
extern uint8_t test_permit;//0-????? 1-????
extern uint8_t repairmode_flag;//0-not repair  1-repair mode
extern char repair_PPID[30];
extern char memberID[10]; //????
//extern uint8_t reportID_flag;

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0,    		  0,   0, 480, 222, 0, 0x0, 0 },
	{ LISTBOX_CreateIndirect, "Listbox", ID_LISTBOX_0, 		 40,  55, 320, 145, 0, 0x0, 0 },
	{ DROPDOWN_CreateIndirect, "Dropdown", ID_DROPDOWN_0, 140,  30,  80,  20, 0, 0x0, 0 },
	{ TEXT_CreateIndirect, "Filebowser", ID_TEXT_0, 			 40,  32,  80,  20, 0, 0x0, 0 },
	{ TEXT_CreateIndirect, "FileInfo", ID_TEXT_1, 			 240,  32,  120,  20, 0, 0x0, 0 },
	//{ TEXT_CreateIndirect, "LockInfo", ID_TEXT_LOCKINFO, 240,  32,  125,  20, 0, 0x0, 0 },
  //{ TREEVIEW_CreateIndirect, "Treeview", ID_TREEVIEW_0, 16, 34, 138, 100, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "PPID:", ID_TEXT_PPID_TITLE, 400, 55, 40, 20, 0, 0x0, 0 },
	{ MULTIEDIT_CreateIndirect, "PPID_INFO", ID_TEXT_PPID, 360, 75, 110, 60, 0, 0x0, 0 },
	{ TEXT_CreateIndirect, "测试模式", ID_TEXT_TESTMODEINF, 390, 140, 80, 20, 0, 0x0, 0 },
	{ TEXT_CreateIndirect, "IMS测试", ID_TEXT_TESTMODE, 390, 165,80, 20, 0, 0x0, 0 },
	{	BUTTON_CreateIndirect, "确定", ID_BUTTON_OK, 160, 200, 80, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "取消", ID_BUTTON_CANCEL, 240, 200, 80, 20, 0, 0x0, 0 },

  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN                hItem;
	WM_MESSAGE             Msg;
	WM_HWIN                hIteminfo;
	int 									  i;
	uint8_t     					sel;
	uint8_t     					items;
//	uint8_t               req_cnt = 0;
	
	hItem = pMsg->hWin;
	WINDOW_SetBkColor(hItem, GUI_LIGHTGRAY);
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0);
	//WM_SetFocus(hItem);
	//更新PPID信息
	if(repairmode_flag == 1)//0-not repair  1-repair mode
	{
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_PPID);
    MULTIEDIT_SetFont(hItem,&GUI_FontHZ12);
		MULTIEDIT_SetTextColor(hItem,MULTIEDIT_CI_READONLY,GUI_RED);
		MULTIEDIT_SetText(hItem,repair_PPID);
		MULTIEDIT_SetMaxNumChars(hItem,50);
		MULTIEDIT_SetAutoScrollV(hItem,1);
		MULTIEDIT_SetWrapWord(hItem);
		WM_ShowWindow(hItem);
	}
	else if(strlen(memberID)!=0)
	{
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_PPID);
    MULTIEDIT_SetFont(hItem,&GUI_FontHZ12);
		MULTIEDIT_SetTextColor(hItem,MULTIEDIT_CI_READONLY,GUI_RED);
		MULTIEDIT_SetText(hItem,memberID);
		MULTIEDIT_SetMaxNumChars(hItem,50);
		MULTIEDIT_SetAutoScrollV(hItem,1);
		MULTIEDIT_SetWrapWord(hItem);
		WM_ShowWindow(hItem);
	}
	
  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
		test_permit = 0;
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetFont(hItem,&GUI_FontHZ12);
    TEXT_SetText(hItem, "测试文件选择");  
	
		hIteminfo = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetFont(hIteminfo,&GUI_FontHZ12);
		TEXT_SetTextColor(hIteminfo,GUI_RED);
		TEXT_SetText(hIteminfo, (char *)"打开测试文件……");
		WM_HideWindow(hIteminfo);
	
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_LOCKINFO);
    TEXT_SetFont(hItem,&GUI_FontHZ12);
		TEXT_SetTextColor(hItem,GUI_RED);
		TEXT_SetText(hItem, "系统被锁定,请解锁!");
		WM_HideWindow(hItem);
	
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_PPID_TITLE);
    TEXT_SetFont(hItem,&GUI_FontHZ12);
		TEXT_SetTextColor(hItem,GUI_RED);
		WM_ShowWindow(hItem);
	

	  //初始化文件选择下拉框
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_0);
		DROPDOWN_SetFont(hItem,&GUI_FontHZ12);
		//if(k_StorageGetStatus(USB_DISK_UNIT) != 0)
    DROPDOWN_AddString(hItem, "U盘");
		//if(k_StorageGetStatus(MSD_DISK_UNIT) != 0)
    DROPDOWN_AddString(hItem, "SD卡");
		if(k_StorageGetStatus(MSD_DISK_UNIT) != 0)
		DROPDOWN_SetSel(hItem,1);
		else DROPDOWN_SetSel(hItem,0);
		
		//初始化文件列表
    //
		store_dev=DROPDOWN_GetSel(hItem);
		WT_TestFolder_Init();
		
	  hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0);
		for(i=0;i<TestFolder->number_TotalFile;i++)
		{
			LISTBOX_AddString(hItem, (char *)TestFolder->FilesName[i]);
		}
		LISTBOX_SetFont(hItem,GUI_FONT_20_1);
		LISTBOX_SetSel(hItem,TestFolder->number_CurrentFile);
		//显示连接方式
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_TESTMODEINF);
    TEXT_SetFont(hItem,&GUI_FontHZ12);
		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_TESTMODE);
    TEXT_SetFont(hItem,&GUI_FontHZ12);
		TEXT_SetTextColor(hItem,GUI_RED);
		if(WT_Config.IMS_Mode == 0)
		{
			TEXT_SetText(hItem, "IMS测试"); 
		}
		else { TEXT_SetText(hItem, "本地测试"); }
		

		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_OK);
		BUTTON_SetFont(hItem,&GUI_FontHZ12);
		BUTTON_SetSkinClassic(hItem);
		BUTTON_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    BUTTON_SetBkColor(hItem,BUTTON_CI_UNPRESSED, GUI_GREEN);
		BUTTON_SetFocussable(hItem,0);//不接收焦点
		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_CANCEL);
		BUTTON_SetFont(hItem,&GUI_FontHZ12);
		BUTTON_SetSkinClassic(hItem);
		BUTTON_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    BUTTON_SetBkColor(hItem,BUTTON_CI_UNPRESSED, GUI_RED);
		BUTTON_SetFocussable(hItem,0);//不接收焦点
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
	case MY_MESSAGE_CLICK:
		GUI_SendKeyMsg(GUI_KEY_TAB, 1);//改变输入焦点
		hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0);
		if(WM_HasFocus(hItem))
		{
			LISTBOX_SetSel(hItem,0);
		}
		break;
	case MY_MESSAGE_DOWN:
		hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0);
		if(WM_HasFocus(hItem))
		{
			LISTBOX_IncSel(hItem);
		}
		hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_0);
		if(WM_HasFocus(hItem))
		{
			sel=DROPDOWN_GetSel(hItem);
			if(sel<1)
			{
				DROPDOWN_IncSel(hItem);
			}					
			else //sel>=1 
			{
				DROPDOWN_SetSel(hItem,0);		
			}	

			store_dev=DROPDOWN_GetSel(hItem);
			WT_TestFolder_Init();
			hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0);
			items = LISTBOX_GetNumItems(hItem);
			for(i=0;i<items;i++)
			{
				LISTBOX_DeleteItem(hItem,0);
			}
			for(i=0;i<TestFolder->number_TotalFile;i++)
			{
				LISTBOX_AddString(hItem, (char *)TestFolder->FilesName[i]);
			}
		}	

		break;
		case MY_MESSAGE_UP:
		hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0);
		if(WM_HasFocus(hItem))
		{
			LISTBOX_DecSel(hItem);
		}
		hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_0);
		if(WM_HasFocus(hItem))
		{
			sel=DROPDOWN_GetSel(hItem);
			if(sel>0)
			{
				DROPDOWN_DecSel(hItem);
			}					
			else //sel>=1 
			{
				DROPDOWN_SetSel(hItem,1);		
			}	

			store_dev=DROPDOWN_GetSel(hItem);
			WT_TestFolder_Init();
			hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0);
			items = LISTBOX_GetNumItems(hItem);
			for(i=0;i<items;i++)
			{
				LISTBOX_DeleteItem(hItem,0);
			}
			for(i=0;i<TestFolder->number_TotalFile;i++)
			{
				LISTBOX_AddString(hItem, (char *)TestFolder->FilesName[i]);
			}
		}

		break;
	case MY_MESSAGE_CANCEL://取消
		repairmode_flag = 0;
		TestFile->command=2;//test cancel
		TestFile->item_total=0;
	    TestFile->file_status = 0;
		GUI_EndDialog(pMsg->hWin,0);
		break;
	case MY_MESSAGE_OK:
		hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0);
		if(LISTBOX_GetNumItems(hItem) ==0 ) break;
			TestFolder->number_CurrentFile=LISTBOX_GetSel(hItem);
	
		hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_0);
		store_dev=DROPDOWN_GetSel(hItem);
		TestFile->command = 0;
		hIteminfo = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
		TEXT_SetText(hIteminfo, (char *)"读取测试文件！");
		WM_ShowWindow(hIteminfo);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_PPID);
		if(strlen(repair_PPID)!=0 && repairmode_flag == 1)//显示PPID信息
		{
			TEXT_SetText(hItem, repair_PPID);	
			WM_ShowWindow(hItem);
		}
		else if(strlen(memberID)!=0)
		{
			TEXT_SetText(hItem, memberID);	
			WM_ShowWindow(hItem);
		}
		else WM_HideWindow(hItem);
		GUI_Exec();
		//WT_TestItem_Init((char *)TestFolder.FilesName[TestFolder.number_CurrentFile]);
		WT_TestItem_Read((char *)TestFolder->FilesName[TestFolder->number_CurrentFile]);
	  if(TestFile->file_status == 1 && WT_Config.IMS_Mode == 0)//文件读取OK,并且处于IMS测试模式,需要同IMS服务器认证
		{
//			test_req:
			if(repairmode_flag == 1)//0-not repair  1-repair mode
			{
				osMessagePut(Uart24GHzEvent, Uart24GHZ_IMSREPAIR_Event, 0);	//发送维修请求信息
				
			}
			else osMessagePut(Uart24GHzEvent, Uart24GHZ_IMSTEST_Event, 0);//发送测试请求信息
			
            for(i=0;i<100;i++) 
            {
                if(test_permit == 1) 
                {
                   break;
                }
                osDelay(50);
            }
			
			if(test_permit == 1) 
			{
				repairmode_flag = 0;
				Msg.MsgId = MY_MESSAGE_BUTTONOK;
				WM_SendMessage(pMsg->hWinSrc,&Msg);
				GUI_EndDialog(pMsg->hWin,0);
			}
			else 
			{
				TEXT_SetText(hIteminfo, (char *)"程序名错误!");
				GUI_Exec();
				//goto dialog_loop;
			}

		}
		else if(TestFile->file_status == 1 && WT_Config.IMS_Mode == 1)
		{
			Msg.MsgId = MY_MESSAGE_BUTTONOK;
			WM_SendMessage(pMsg->hWinSrc,&Msg);
			GUI_EndDialog(pMsg->hWin,0);
		}
		else
		{
			TEXT_SetText(hIteminfo, (char *)"读取测试文件错误!");
			WM_ShowWindow(hIteminfo);
		}


//		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_CANCEL);
//		if(WM_HasFocus(hItem))//取消
//		{
//			TestFolder->number_CurrentFile=0;
//			TestFile->command = 0;
//			WT_TestItem_Init(TestFolder->FilesName[0]);
//			Msg.MsgId = MY_MESSAGE_BUTTONCANCEL;
//			WM_SendMessage(pMsg->hWinSrc,&Msg);
//			GUI_EndDialog(pMsg->hWin,0);
//		}
		//GUI_EndDialog(pMsg->hWin,0);
		//Number_Windos = 0;
		break;
	case MY_MESSAGE_LOCK:
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
		WM_HideWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_LOCKINFO);
		TEXT_SetText(hItem, "系统被锁定，请解锁！");
		WM_ShowWindow(hItem);
		GUI_Exec();
		break;
	case MY_MESSAGE_UNLOCK:
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_LOCKINFO);
		WM_HideWindow(hItem);
		break;
	case WM_PAINT://绘制标题栏
		GUI_SetColor(GUI_DARKBLUE);
		GUI_FillRect(0,0,480,22);
		GUI_SetColor(GUI_DARKGRAY);
		GUI_SetPenSize(8);
		GUI_DrawRect(0,0,478,220);
//		GUI_DrawRoundedFrame(0, 0, 480, 222, 0, 4);
    break;
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN Create_TestDlgWindow( WM_HWIN hWin_para);
WM_HWIN Create_TestDlgWindow( WM_HWIN hWin_para) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, hWin_para, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
